package com.smates.dbc2.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-10-29T02:43:58.733+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "IModelEconomicImpl", 
                  wsdlLocation = "http://210.77.68.221:9099/ModelEconomic/IModelEconomicWS?wsdl",
                  targetNamespace = "http://impl.service.hhs.com/") 
public class IModelEconomicImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.hhs.com/", "IModelEconomicImpl");
    public final static QName IModelEconomicImplPort = new QName("http://impl.service.hhs.com/", "IModelEconomicImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://210.77.68.221:9099/ModelEconomic/IModelEconomicWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IModelEconomicImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://210.77.68.221:9099/ModelEconomic/IModelEconomicWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IModelEconomicImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IModelEconomicImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IModelEconomicImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IModelEconomicImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IModelEconomicImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IModelEconomicImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IModelEconomic
     */
    @WebEndpoint(name = "IModelEconomicImplPort")
    public IModelEconomic getIModelEconomicImplPort() {
        return super.getPort(IModelEconomicImplPort, IModelEconomic.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IModelEconomic
     */
    @WebEndpoint(name = "IModelEconomicImplPort")
    public IModelEconomic getIModelEconomicImplPort(WebServiceFeature... features) {
        return super.getPort(IModelEconomicImplPort, IModelEconomic.class, features);
    }

}
